import { SOCKET_EVENTS } from "../Utils/socketConstants.js";

/**
 * Event registry. Each entry defines the channels used by the notification
 * service. Per the deployment constraint: general notifications use socket + push (FCM);
 * SMS is used for OTP and critical transaction alerts; WhatsApp/email adapters exist
 * for quotation and transactional flows.
 */
export const NOTIFICATION_EVENTS = {
  // 👑 ADMIN & OWNER EVENTS
  NEW_BOOKING: {
    defaultChannels: ["socket"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.NEW_BOOKING,
    recipientTypes: ["admin"],
  },
  BOOKING_AT_RISK: {
    defaultChannels: ["socket"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.BOOKING_AT_RISK,
    recipientTypes: ["admin"],
  },
  COMPLAINT_SLA_BREACH: {
    defaultChannels: ["socket"],
    priority: "high",
    category: "complaint",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.COMPLAINT_SLA_BREACH,
    recipientTypes: ["admin"],
  },
  REFUND_MANUAL_REVIEW: {
    defaultChannels: ["socket"],
    priority: "critical",
    category: "financial",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.REFUND_MANUAL_REVIEW,
    recipientTypes: ["admin"],
  },
  ADMIN_UNREAD_COUNTS_UPDATED: {
    defaultChannels: ["socket"],
    priority: "normal",
    category: "system",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.ADMIN_UNREAD_COUNTS_UPDATED,
    recipientTypes: ["admin"],
  },

  // 🔧 TECHNICIAN EVENTS
  JOB_NEW: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.JOB_NEW,
    recipientTypes: ["technician"],
  },
  JOB_BROADCAST: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.JOB_BROADCAST,
    recipientTypes: ["technician"],
  },
  JOB_EXPIRED: {
    defaultChannels: ["socket"],
    priority: "normal",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.JOB_EXPIRED,
    recipientTypes: ["technician"],
  },
  JOB_CANCELLED_BY_CUSTOMER: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.JOB_CANCELLED_BY_CUSTOMER,
    recipientTypes: ["technician"],
  },
  TRAVEL_REMINDER: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.TRAVEL_REMINDER,
    recipientTypes: ["technician"],
  },
  PAYMENT_RECEIVED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "payout",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.PAYMENT_RECEIVED,
    recipientTypes: ["technician"],
  },
  AUTO_PAYOUT_PAID: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "payout",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.AUTO_PAYOUT_PAID,
    recipientTypes: ["technician"],
  },
  WITHDRAWAL_FAILED: {
    defaultChannels: ["socket", "push"],
    priority: "critical",
    category: "payout",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.WITHDRAWAL_FAILED,
    recipientTypes: ["technician", "admin"],
  },
  COMPLAINT_FILED_AGAINST_YOU: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "complaint",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.COMPLAINT_FILED_AGAINST_YOU,
    recipientTypes: ["technician"],
  },
  CLAWBACK_APPLIED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "financial",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.CLAWBACK_APPLIED,
    recipientTypes: ["technician"],
  },
  HOLD_RELEASED: {
    defaultChannels: ["socket", "push"],
    priority: "normal",
    category: "financial",
    dndAllowed: true,
    socketEvent: SOCKET_EVENTS.HOLD_RELEASED,
    recipientTypes: ["technician"],
  },
  PERMISSION_STATUS_CHANGED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "system",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.PERMISSION_STATUS_CHANGED,
    recipientTypes: ["technician"],
  },

  // 👤 CUSTOMER / USER EVENTS
  OTP: {
    defaultChannels: ["sms", "whatsapp"],
    priority: "critical",
    category: "security",
    dndAllowed: false,
    preferenceRequired: false,
    recipientTypes: ["customer", "technician"],
  },
  BOOKING_ACCEPTED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.JOB_ACCEPTED_NOTIFY,
    recipientTypes: ["customer"],
  },
  TECHNICIAN_TRAVEL_STARTED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.TECHNICIAN_STARTED_TRAVEL,
    recipientTypes: ["customer"],
  },
  TECHNICIAN_ARRIVED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.TECHNICIAN_ARRIVED,
    recipientTypes: ["customer"],
  },
  BOOKING_COMPLETED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.BOOKING_COMPLETED,
    recipientTypes: ["customer"],
  },
  BOOKING_CANCELLED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "booking",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.BOOKING_CANCELLED,
    recipientTypes: ["customer", "technician", "admin"],
  },
  PAYMENT_SUCCESS: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "payment",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.PAYMENT_SUCCESS,
    recipientTypes: ["customer", "admin"],
  },
  REFUND_INITIATED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "financial",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.REFUND_INITIATED,
    recipientTypes: ["customer"],
  },
  REFUND_PROCESSED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "financial",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.REFUND_PROCESSED,
    recipientTypes: ["customer"],
  },
  REFUND_FAILED: {
    defaultChannels: ["socket", "push"],
    priority: "critical",
    category: "financial",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.REFUND_FAILED,
    recipientTypes: ["customer", "admin"],
  },
  QUOTATION_SENT: {
    defaultChannels: ["socket", "push", "whatsapp"],
    priority: "high",
    category: "quotation",
    dndAllowed: false,
    socketEvent: "quotation:sent",
    recipientTypes: ["customer"],
  },
  COMPLAINT_RECEIVED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "complaint",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.COMPLAINT_RECEIVED,
    recipientTypes: ["customer", "technician", "admin"],
  },
  COMPLAINT_UNDER_REVIEW: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "complaint",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.COMPLAINT_UNDER_REVIEW,
    recipientTypes: ["customer", "technician"],
  },
  COMPLAINT_REJECTED: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "complaint",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.COMPLAINT_REJECTED,
    recipientTypes: ["customer"],
  },
  COMPLAINT_RESOLVED_IN_FAVOUR: {
    defaultChannels: ["socket", "push"],
    priority: "high",
    category: "complaint",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.COMPLAINT_RESOLVED_IN_FAVOUR,
    recipientTypes: ["customer", "technician"],
  },
  COMPLAINT_STATUS_UPDATED: {
    defaultChannels: ["socket", "push"],
    priority: "normal",
    category: "complaint",
    dndAllowed: false,
    socketEvent: SOCKET_EVENTS.COMPLAINT_STATUS_UPDATED,
    recipientTypes: ["admin"],
  },
};

export const isValidEventType = (t) => Object.prototype.hasOwnProperty.call(NOTIFICATION_EVENTS, t);

export const getEventPolicy = (t) => NOTIFICATION_EVENTS[t] || null;
