import mongoose from "mongoose";

const withdrawalRequestSchema = new mongoose.Schema(
  {
    technicianId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "TechnicianProfile",
      required: true,
      index: true,
    },

    amount: {
      type: Number,
      required: true,
      min: 1,
    },

    // Integer paise (primary financial field)
    amountPaise: {
      type: Number,
      default: null,
      min: 0,
    },

    // 💵 Financial breakdown for withdrawal (in Paise & Rupees)
    requestedAmountPaise: {
      type: Number,
      default: null,
      min: 0,
    },
    commissionDeductionPaise: {
      type: Number,
      default: 0,
      min: 0,
    },
    penaltyDeductionPaise: {
      type: Number,
      default: 0,
      min: 0,
    },
    penaltyReason: {
      type: String,
      default: null,
      trim: true,
    },
    otherDeductionsPaise: {
      type: Number,
      default: 0,
      min: 0,
    },
    netPayoutAmountPaise: {
      type: Number,
      default: null,
      min: 0,
    },

    // 💸 Payout origin: "technician_request" | "admin_direct" | "auto"
    origin: {
      type: String,
      enum: ["technician_request", "admin_direct", "auto"],
      default: "technician_request",
    },

    // requiresApproval is true only for technician_request origin.
    // admin_direct and auto are pre-approved / pre-processed.
    requiresApproval: {
      type: Boolean,
      default: false,
    },

    // clientIdempotencyKey is generated by the UI when the payout form is opened.
    // It is sent on every attempt to prevent double-click double-payout.
    clientIdempotencyKey: {
      type: String,
      default: null,
    },

    // initiatedBy tracks who/what started this payout.
    initiatedBy: {
      actorType: {
        type: String,
        enum: ["technician", "admin", "system"],
        default: "admin",
      },
      actorId: {
        type: mongoose.Schema.Types.ObjectId,
        default: null,
      },
    },

    // Auto-payout fields — set only for origin === "auto". Auto requests are
    // created pre-approved (no admin step) and processed by the same
    // Razorpay X outbox engine as manual ones.
    autoApproved: {
      type: Boolean,
      default: false,
    },
    autoApprovedAt: {
      type: Date,
      default: null,
    },
    autoApprovedReason: {
      type: String,
      default: null,
      trim: true,
    },
    // Maintenance floor kept in the wallet when the auto-payout ran
    minimumMaintenancePaise: {
      type: Number,
      default: null,
      min: 0,
    },

    status: {
      type: String,
      enum: [
        "pending",
        "requested",
        "approved",
        "rejected",
        "paid",
        "cancelled",
        "processing",
        "failed",
        "manual_review",
      ],
      default: "pending",
      index: true,
    },

    requestedAt: {
      type: Date,
      default: Date.now,
    },

    approvedAt: {
      type: Date,
      default: null,
    },

    rejectedAt: {
      type: Date,
      default: null,
    },

    paidAt: {
      type: Date,
      default: null,
    },

    failedAt: {
      type: Date,
      default: null,
    },

    decidedAt: {
      type: Date,
      default: null,
    },
    decidedBy: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
      index: true,
    },
    //sk

    adminNote: {
      type: String,
      default: null,
      trim: true,
    },

    decisionNote: {
      type: String,
      default: null,
      trim: true,
    },

    payoutProvider: {
      type: String,
      default: null,
      trim: true,
    },

    payoutReference: {
      type: String,
      default: null,
      trim: true,
      index: true,
    },

    // Masked payout destination shown in technician/admin history.
    // e.g. "****1234" (bank) or "vi***@okhdfcbank" (UPI). Never the full number.
    payoutDestination: {
      type: String,
      default: null,
      trim: true,
    },

    // "UPI" | "IMPS" — the RazorpayX mode used for the payout.
    payoutMode: {
      type: String,
      default: null,
      trim: true,
    },

    utr: {
      type: String,
      default: null,
      trim: true,
      index: true,
    },

    // Human-readable failure reason (non-empty only on failed payouts).
    failureReason: {
      type: String,
      default: null,
      trim: true,
    },

    walletTransactionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "WalletTransaction",
      default: null,
      index: true,
    },

    payoutOutboxId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "PayoutOutbox",
      default: null,
    },
  },
  { timestamps: true }
);

// ✅ Prevent duplicate active payouts per technician.
// One active payout per technician, regardless of origin.
// This blocks admin double-click and concurrent technician requests.
withdrawalRequestSchema.index(
  { technicianId: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: {
        $in: ["pending", "requested", "approved", "processing", "manual_review"],
      },
    },
    name: "uniq_active_payout_per_technician",
  }
);

// 🔐 Idempotency key — unique sparse index. Two clicks with the same key
// return the existing record; different keys are blocked by the partial index above.
withdrawalRequestSchema.index(
  { clientIdempotencyKey: 1 },
  { unique: true, sparse: true }
);

// Admin list/summary hot paths (status filters + date ranges)
withdrawalRequestSchema.index({ status: 1, createdAt: 1 });

// Admin list with no status filter sorts by createdAt alone (S12)
withdrawalRequestSchema.index({ createdAt: -1 });

// 💸 Auto-payout race guard — at most ONE active auto withdrawal per tech.
// Two cron runs (or a cron run + manual flow) can never both reserve the
// same balance: the second insert fails with a duplicate-key error.
withdrawalRequestSchema.index(
  { technicianId: 1, origin: 1, status: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: { $in: ["pending", "requested", "approved", "processing"] },
    },
  }
);

// Auto-payout admin summary hot paths (counts by origin+status)
withdrawalRequestSchema.index({ origin: 1, status: 1, createdAt: -1 });

export default mongoose.models.WithdrawalRequest ||
  mongoose.model("WithdrawalRequest", withdrawalRequestSchema);